dist: focal
language: c

os: linux

compiler: gcc

install:
    - sudo apt-get install valgrind
    - sudo apt-get install clang
    - sudo apt-get install cppcheck

script:
    - cd project/
    - mkdir build
    - cd build
    - cmake ..
    - make clean && make
    - valgrind --tool=memcheck --leak-check=full ./test.out ../db.txt ../search.txt
