dist: focal
language: c

os: linux

compiler: gcc

install:
    - sudo apt-get install valgrind
    - sudo apt-get install clang
    - sudo apt-get install cppcheck

script:
    - cd project/
    - mkdir build
    - cd build
    - cmake ..
    - make clean && make
    - cd ..
    - cp db.txt /build
    - cp search.txt / build
    - cd build
    - ./test.out db.txt search.txt


after_success:
  - bash <(curl -s https://codecov.io/bash)
